#!/bin/sh
set +e
if ! [ -f /.dockerenv ]; then
  echo "Running in docker image problemtools/icpc..."
  exec sudo docker run --rm -it -v "$PWD":/problems -w /problems problemtools/icpc ./verifyall "$@"
fi
if ! command -v verifyproblem > /dev/null; then
  echo "verifyproblem command not found!"
  exit 1
fi
h1="=================================================="
h2="--------------------------------------------------"
res=0
gen_fails=""
ver_fails=""
for f in */problem.yaml; do
  p=$(dirname "$f")
  echo "$h1"
  echo "Problem: $p"
  echo "$h1"
  echo
  cd "$p"
  if [ -f data/generator.sh ]; then
    echo "$h2"
    echo "$p: Test case generation"
    echo "$h2"
    echo
    (cd data && ./generator.sh)
    gen_status=$?
    res=$((res + gen_status))
    if [ "$gen_status" -ne 0 ]; then
  	  gen_fails="${gen_fails}${p}\n"
    fi
  fi
  cd ".."
  echo
  echo "$h2"
  echo "$p: Problem verification"
  echo "$h2"
  echo
  if [ "$gen_status" -eq 0 ]; then
	verifyproblem "$p"
	ver_status=$?
	if [ "$ver_status" -ne 0 ]; then
	  ver_fails="${ver_fails}${p}\n"
	fi
	res=$((res + ver_status))
  else
	echo "Skipped due to failed test generation."
  fi
  echo
  echo
  echo
done
if [ "$res" -ne 0 ]; then
  echo "$h1"
  echo "Verification of all problems failed"
  echo "$h1"
  echo
  echo "Problems failing test generation:"
  echo "$gen_fails"
  echo
  echo "Problems failing problem verification:"
  echo "$ver_fails"
fi
exit $res
